"repositories for java 21"

#VERSION 21.0.12

java = use_extension("//private/extensions:java.bzl", "java")
java.archive(
    name = "temurin21_jre_amd64",
    architecture = "amd64",
    plain_version = "21.0.12",
    sha256 = "2413149700df0f7d440500a84a8f764c535f21e5a5e87d38328b64eec2c5b500",
    strip_prefix = "jdk-21.0.12.1+1-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_x64_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jdk_amd64",
    architecture = "amd64",
    plain_version = "21.0.12",
    sha256 = "ce79869e1307ed8ee1e2baa86a412b1eb5b75d10a01006d788a6f968bcfaee94",
    strip_prefix = "jdk-21.0.12.1+1",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_x64_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jre_arm64",
    architecture = "arm64",
    plain_version = "21.0.12",
    sha256 = "14be1f35ebdbd1f6e8d57eb911a3ffb74d6d9aa255abc5daf2b1302002cf2cf2",
    strip_prefix = "jdk-21.0.12.1+1-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jdk_arm64",
    architecture = "arm64",
    plain_version = "21.0.12",
    sha256 = "23e37e026f12f3e706f18938ff611db3032d075b09d0879a25d06718c773e223",
    strip_prefix = "jdk-21.0.12.1+1",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jre_s390x",
    architecture = "s390x",
    plain_version = "21.0.12",
    sha256 = "df43dc82a935868915a4b76227e2c63ffeb32868b608980dc67312a3d6217e1e",
    strip_prefix = "jdk-21.0.12.1+1-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_s390x_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jdk_s390x",
    architecture = "s390x",
    plain_version = "21.0.12",
    sha256 = "806bb29b0d408eb6312cda0a1e756bc91e554ef9ed6a5863f6004e502f6c789a",
    strip_prefix = "jdk-21.0.12.1+1",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_s390x_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jre_ppc64le",
    architecture = "ppc64le",
    plain_version = "21.0.12",
    sha256 = "d2f07f1d97faab23b3add1af92db402b721b5b251cedab7144fdd4b2bf2e2f13",
    strip_prefix = "jdk-21.0.12.1+1-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jre_ppc64le_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
java.archive(
    name = "temurin21_jdk_ppc64le",
    architecture = "ppc64le",
    plain_version = "21.0.12",
    sha256 = "042482fa372f12741ceb721397e277b4e69672182aaa45a1bf7af55d9ba876d6",
    strip_prefix = "jdk-21.0.12.1+1",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_ppc64le_linux_hotspot_21.0.12.1_1.tar.gz"],
    version = "21.0.12.1+1",
)
